name: Build Release

on:
  push:
    tags:
      - 'v*.*.*'  # Match version tags

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        submodules: true
        fetch-depth: 0
        persist-credentials: false

    - name: Set Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --verbose

    - uses: Nuitka/Nuitka-Action@main
      name: Build Windows version
      with:
        script-name: main.py
        onefile: true
        enable-plugins: pyside6
        disable-console: true
        windows-icon-from-ico: src/Ui/resource/image/icon.ico
        output-filename: "NapCat-Desktop"

    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Add manifest file
      run: |
        mt.exe -manifest ./assets/NapCat-Desktop.exe.manifest -outputresource:./build/NapCat-Desktop.exe;1

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: NapCat-Desktop
        path: ./build/NapCat-Desktop.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          submodules: true
          fetch-depth: 0
          persist-credentials: false

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: NapCat-Desktop

      - name: Set tag and body content
        id: get_info
        run: |
          TAG_NAME=$(echo "${GITHUB_REF#refs/tags/}")
          BODY=$(cat docs/CHANGELOG.md)
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "BODY<<EOF" >> $GITHUB_ENV
          echo "$BODY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create release draft
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: "./NapCat-Desktop.exe"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.TAG_NAME }}
          name: NapCat Desktop Release ${{ env.TAG_NAME }}
          body: ${{ env.BODY }}
